# Workflow to generate doxygen and publish them
# to a github pages.
name: Doxygen Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Generate Documentation
        run: doxgen doc/Doxyfile
        shell: bash
      
      - name: Create .nojekyll (ensures pages with underscores work on gh pages)
        run: doc/html/.nojekyll
        shell: bash
      
      -name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: doc/html