# Workflow to generate doxygen and publish them
# to a github pages.
name: Doxygen Publish

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    #using: "composite"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Generate Documentation
        run: doxygen doc/Doxyfile
        shell: bash
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: doc/html